### ISSUE TITLE
Validação IE para AM

### ISSUE THREAD

**Issue by edmaarcosta** [Pull4up/br_inscricao_estadual#5]
Vi que a validação de inscrição estadual para o estado do Amazonas foi corrigido, porém não foi atualizado a versão a gem.
Até criei um fork para criar uma gem mais atualizada, porém, acredito que isso não seja muito correto.

Gostaria de saber se a gem será atualizada.

Agradeço desde já. Aguardo retorno.

**Comment by ypoloni** [comment]
Ola @edmaarcosta,

Acabei de atualizar a gem no ruby gems, realmente eu havia esquecido. 
Se você precisar de alguma gem que está mais atualizada no git do que no ruby gems você pode setar para busca-la diretamente do repositorio Git ;)!

Eu que agradeço, Obrigado.
